"use strict"

const bcrypt = require("bcryptjs")
const {
  supabase,
  supabaseAuth,
  getCachedUser,
  cacheUser,
  invalidateAuthCache,
} = require("./db")

// ── JWT auth (mobile users via Supabase Auth) ───────────

/**
 * Require a valid Supabase JWT in the Authorization
 * header. Sets req.userId and req.userEmail.
 *
 * @param {import("express").Request} req
 * @param {import("express").Response} res
 * @param {import("express").NextFunction} next
 */
async function requireJwt(req, res, next) {
  const auth = req.headers.authorization
  if (!auth?.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Unauthorized" })
  }
  const token = auth.slice(7)

  const { data, error } = await supabaseAuth.auth.getUser(token)
  if (error || !data?.user) {
    return res.status(401).json({ error: "Invalid token" })
  }

  req.userId = data.user.id
  req.userEmail = data.user.email
  next()
}

// ── API key auth (local sync client) ────────────────────

/**
 * Require a valid API key in the Authorization header.
 * Checks all users with a key hash and caches positive
 * matches. Sets req.userId and req.userPlan.
 *
 * @param {import("express").Request} req
 * @param {import("express").Response} res
 * @param {import("express").NextFunction} next
 */
async function requireApiKey(req, res, next) {
  const auth = req.headers.authorization
  if (!auth?.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Unauthorized" })
  }
  const apiKey = auth.slice(7)

  // Fast path: check SHA-256 cache (no bcrypt, no DB)
  const cached = getCachedUser(null, apiKey)
  if (cached) {
    req.userId = cached.id
    req.userPlan = cached.plan
    return next()
  }

  // Look up candidate by prefix (indexed), then verify
  // with a single bcrypt compare instead of scanning all.
  const prefix = apiKey.slice(0, 8)
  const { data: users } = await supabase
    .from("users")
    .select("id, plan, api_key_hash, api_key_prefix")
    .eq("api_key_prefix", prefix)
    .limit(5)

  if (users) {
    for (const user of users) {
      const match = await bcrypt.compare(
        apiKey, user.api_key_hash,
      )
      if (match) {
        cacheUser(user.id, apiKey, user)
        req.userId = user.id
        req.userPlan = user.plan
        return next()
      }
    }
  }

  // Fallback: scan users without a prefix (pre-migration
  // accounts). Backfill the prefix on successful match.
  const { data: legacy } = await supabase
    .from("users")
    .select("id, plan, api_key_hash")
    .is("api_key_prefix", null)
    .not("api_key_hash", "is", null)
    .limit(200)

  if (legacy) {
    for (const user of legacy) {
      const match = await bcrypt.compare(
        apiKey, user.api_key_hash,
      )
      if (match) {
        // Backfill prefix for future fast lookups
        await supabase
          .from("users")
          .update({ api_key_prefix: prefix })
          .eq("id", user.id)
        cacheUser(user.id, apiKey, user)
        req.userId = user.id
        req.userPlan = user.plan
        return next()
      }
    }
  }

  return res.status(401).json({ error: "Invalid API key" })
}

// ── Combined auth (JWT or API key) ──────────────────────

/**
 * Accept either a Supabase JWT or an API key. Tries JWT
 * first for tokens longer than 50 characters, then falls
 * back to API key auth.
 *
 * @param {import("express").Request} req
 * @param {import("express").Response} res
 * @param {import("express").NextFunction} next
 */
async function requireAuth(req, res, next) {
  const auth = req.headers.authorization
  if (!auth?.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Unauthorized" })
  }

  const token = auth.slice(7)

  // Distinguish JWT vs API key by length. API keys are
  // generated by crypto.randomUUID() (36 chars), while
  // Supabase JWTs are several hundred chars of base64. A
  // token longer than 50 can only be a JWT; one 50 or
  // shorter can only be an API key. The boundary is
  // comfortably wide so any minor format drift on either
  // side stays inside the right branch.
  if (token.length > 50) {
    const { data, error } =
      await supabaseAuth.auth.getUser(token)
    if (!error && data?.user) {
      req.userId = data.user.id
      req.userEmail = data.user.email
      const cached = PLAN_CACHE.get(data.user.id)
      if (
        cached &&
        Date.now() - cached.ts < PLAN_CACHE_TTL
      ) {
        req.userPlan = cached.plan
      } else {
        const { data: u } = await supabase
          .from("users")
          .select("plan")
          .eq("id", data.user.id)
          .maybeSingle()
        const plan = u?.plan || "free"
        PLAN_CACHE.set(
          data.user.id, { plan, ts: Date.now() },
        )
        req.userPlan = plan
      }
      return next()
    }
  }

  return requireApiKey(req, res, next)
}

// ── Plan enforcement ────────────────────────────────────

/**
 * Require the authenticated user to be on one of the
 * given plans. Returns 403 if not.
 *
 * @param {...string} plans - Allowed plan names.
 * @returns {Function} Express middleware.
 */
// Cache plan lookups to avoid a Supabase round-trip on
// every request (free tier can be 100-300ms away).
//
// Consequence of the 60s TTL: a downgrade (Stripe webhook
// fires, clearPlanCache called) takes effect immediately
// for the current process, but a delayed webhook means a
// user can keep hitting paid-plan routes for up to one
// minute after their subscription ends in Stripe. Accepted
// trade-off — the per-request DB hit on every paid plan
// check would dominate latency for the AI gateway, which
// is the hottest path.
const PLAN_CACHE = new Map()
const PLAN_CACHE_TTL = 60_000

function requirePlan(...plans) {
  return async (req, res, next) => {
    const userId = req.userId
    const cached = PLAN_CACHE.get(userId)
    if (cached && Date.now() - cached.ts < PLAN_CACHE_TTL) {
      if (!plans.includes(cached.plan)) {
        return res.status(403).json({
          error: "Plan upgrade required",
          current_plan: cached.plan,
        })
      }
      req.userPlan = cached.plan
      return next()
    }

    let { data: user } = await supabase
      .from("users")
      .select("plan")
      .eq("id", userId)
      .single()

    if (!user) {
      const { data: created } = await supabase
        .from("users")
        .upsert({ id: userId, plan: "free" })
        .select("plan")
        .single()
      user = created
    }

    const plan = user?.plan || "free"
    PLAN_CACHE.set(userId, { plan, ts: Date.now() })

    if (!plans.includes(plan)) {
      return res.status(403).json({
        error: "Plan upgrade required",
        current_plan: plan,
      })
    }
    req.userPlan = plan
    next()
  }
}

/**
 * Invalidate every cached copy of a user's plan so a
 * plan change takes effect on the next request.
 *
 * Two caches hold the plan with different lifetimes:
 *   - PLAN_CACHE here (60s), read by requirePlan
 *   - the auth cache in db.js (5min), which stores the
 *     whole user row (incl. plan) keyed by API-key hash
 *     and is read by requireApiKey to skip bcrypt
 *
 * Clearing only the first let a plan change lag up to 5
 * minutes behind. Clear both so an upgrade / downgrade
 * (Stripe webhook, billing) is effective immediately.
 *
 * @param {string} userId - User UUID.
 */
function clearPlanCache(userId) {
  PLAN_CACHE.delete(userId)
  invalidateAuthCache(userId)
}

module.exports = {
  requireJwt,
  requireApiKey,
  requireAuth,
  requirePlan,
  clearPlanCache,
}
